 ORG 0000H
; FOR INTERNAL MEMORY
	MOV R0, #40H	; STORE INTERNAL MEMORY ADDRESS IN RO
	MOV A, #00H	; CLEAR ACCUMULATOR
	MOV R7, #07H	; COUNTER REGISTER
BACK :	MOV B,@R0
		ADD A,B	;
	INC R0		; NEXT VALUE
	DJNZ R7, BACK	;
	END
